/* ============================================================
   BlockCraft Planner — built-in blueprint templates
   Format: layers are listed bottom → top. Each layer is an array
   of strings (one per z-row, front row first); each character is
   one block, mapped through `legend`. '.' is always air/empty.
   Every row must be exactly `width` chars and every layer exactly
   `depth` rows — validated by tools/validate.mjs and at load time.
   ============================================================ */

const TEMPLATES = [
  /* ---------------------------------------------------------- */
  {
    id: "starter_house",
    name: "Starter House",
    category: "Shelter",
    difficulty: "Beginner",
    description:
      "A classic 9×7 oak-and-cobblestone home — the first house every world needs. " +
      "Log corner posts frame plank walls, with a proper stair roof so it doesn't look like a box.",
    tips: [
      "Build the cobblestone foundation first and check it's level.",
      "Place the roof stairs facing inward so they step up toward the ridge.",
      "Light the inside with torches or lanterns before nightfall.",
    ],
    legend: {
      C: "cobblestone",
      P: "oak_planks",
      L: "oak_log",
      G: "glass_pane",
      D: "oak_door",
      S: "oak_stairs",
      H: "oak_slab",
    },
    layers: [
      [ // Layer 1 — foundation & floor
        "CCCCCCCCC",
        "CPPPPPPPC",
        "CPPPPPPPC",
        "CPPPPPPPC",
        "CPPPPPPPC",
        "CPPPPPPPC",
        "CCCCCCCCC",
      ],
      [ // Layer 2 — walls + door
        "LPPPDPPPL",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "LPPPPPPPL",
      ],
      [ // Layer 3 — windows (leave the cell above the door empty)
        "LPGP.PGPL",
        "P.......P",
        "G.......G",
        "G.......G",
        "G.......G",
        "P.......P",
        "LPGPGPGPL",
      ],
      [ // Layer 4 — top of walls
        "LPPPPPPPL",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "LPPPPPPPL",
      ],
      [ // Layer 5 — roof, first course
        "SSSSSSSSS",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "P.......P",
        "SSSSSSSSS",
      ],
      [ // Layer 6 — roof, second course
        ".........",
        "SSSSSSSSS",
        "P.......P",
        "P.......P",
        "P.......P",
        "SSSSSSSSS",
        ".........",
      ],
      [ // Layer 7 — ridge
        ".........",
        ".........",
        "SSSSSSSSS",
        "HHHHHHHHH",
        "SSSSSSSSS",
        ".........",
        ".........",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "cozy_cottage",
    name: "Cozy Cottage",
    category: "Shelter",
    difficulty: "Intermediate",
    description:
      "An 11×9 spruce cottage with a mossy cobblestone foundation, a tall stepped roof " +
      "and a working chimney topped with a campfire for that smoking-chimney look.",
    tips: [
      "The campfire on the chimney makes real smoke — put a hay bale under it for taller smoke.",
      "Mossy cobblestone is scattered in the foundation on purpose: texture beats uniformity.",
      "Swap spruce for dark oak accents if you want a tudor look.",
    ],
    legend: {
      C: "cobblestone",
      M: "mossy_cobblestone",
      P: "spruce_planks",
      L: "spruce_log",
      G: "glass_pane",
      D: "spruce_door",
      S: "spruce_stairs",
      H: "spruce_slab",
      f: "campfire",
    },
    layers: [
      [ // Layer 1 — foundation & floor
        "CCMCCCCCMCC",
        "CPPPPPPPPPC",
        "CPPPPPPPPPC",
        "MPPPPPPPPPM",
        "CPPPPPPPPPC",
        "CPPPPPPPPPC",
        "CPPPPPPPPPM",
        "CPPPPPPPPPC",
        "CCCCMCCCCCC",
      ],
      [ // Layer 2 — cobble base course + door
        "LCCCCDCCCCL",
        "C.........C",
        "C.........C",
        "C.........C",
        "C.........C",
        "C.........C",
        "C.........C",
        "C.........C",
        "LCCCCCCCCCL",
      ],
      [ // Layer 3 — plank walls + windows
        "LPGGP.PGGPL",
        "P.........P",
        "G.........G",
        "G.........G",
        "P.........P",
        "G.........G",
        "G.........G",
        "P.........P",
        "LPGGPPPGGPL",
      ],
      [ // Layer 4 — top of walls
        "LPPPPPPPPPL",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "LPPPPPPPPPL",
      ],
      [ // Layer 5 — roof course 1 + chimney base
        "SSSSSSSSSSS",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.......C.P",
        "SSSSSSSSSSS",
      ],
      [ // Layer 6 — roof course 2 + chimney
        "...........",
        "SSSSSSSSSSS",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "P.........P",
        "........C..",
        "SSSSSSSSSSS",
      ],
      [ // Layer 7 — roof course 3 + chimney
        "...........",
        "...........",
        "SSSSSSSSSSS",
        "P.........P",
        "P.........P",
        "P.........P",
        "SSSSSSSSSSS",
        "........C..",
        "...........",
      ],
      [ // Layer 8 — roof course 4 + chimney
        "...........",
        "...........",
        "...........",
        "SSSSSSSSSSS",
        "P.........P",
        "SSSSSSSSSSS",
        "...........",
        "........C..",
        "...........",
      ],
      [ // Layer 9 — ridge + smoking campfire
        "...........",
        "...........",
        "...........",
        "...........",
        "HHHHHHHHHHH",
        "...........",
        "...........",
        "........f..",
        "...........",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "castle_tower",
    name: "Castle Tower",
    category: "Castle",
    difficulty: "Intermediate",
    description:
      "A 9×9 round stone-brick watchtower, 12 blocks tall, with arrow slits, an interior " +
      "ladder, a plank-floored battlement deck and proper crenellations on top.",
    tips: [
      "Mossy and cracked stone bricks are mixed in randomly — that 10–20% scatter is what makes stone look aged.",
      "The ladder runs up the inside back wall; the hole in the deck floor is your hatch.",
      "Build four of these and join them with walls for an instant castle.",
    ],
    legend: {
      S: "stone_bricks",
      M: "mossy_stone_bricks",
      K: "cracked_stone_bricks",
      P: "oak_planks",
      D: "spruce_door",
      L: "ladder",
    },
    layers: [
      [ // Layer 1 — solid base
        "...SSS...",
        ".SSSSSSS.",
        ".SSSSSSS.",
        "SSSSSSSSS",
        "SSSSMSSSS",
        "SSSSSSSSS",
        ".SSSSSSS.",
        ".SSKSSSS.",
        "...SSS...",
      ],
      [ // Layer 2 — walls + door
        "...SDS...",
        ".SS...SS.",
        ".S.....S.",
        "S.......S",
        "S.......S",
        "S.......S",
        ".S.....S.",
        ".SS.L.SS.",
        "...SMS...",
      ],
      [ // Layer 3 — walls (above door open)
        "...S.S...",
        ".SS...SS.",
        ".K.....S.",
        "S.......S",
        "S.......S",
        "S.......M",
        ".S.....S.",
        ".SS.L.SS.",
        "...SSS...",
      ],
      [ // Layer 4
        "...SSS...",
        ".SM...SS.",
        ".S.....S.",
        "S.......S",
        "S.......S",
        "S.......S",
        ".S.....K.",
        ".SS.L.MS.",
        "...SSS...",
      ],
      [ // Layer 5
        "...SSS...",
        ".SS...SS.",
        ".S.....S.",
        "M.......S",
        "S.......S",
        "S.......S",
        ".S.....S.",
        ".SK.L.SS.",
        "...SSS...",
      ],
      [ // Layer 6 — arrow slits (N, S, E, W)
        "...S.S...",
        ".SS...SS.",
        ".S.....S.",
        "S.......S",
        ".........",
        "S.......S",
        ".S.....S.",
        ".SS.L.SS.",
        "...S.S...",
      ],
      [ // Layer 7
        "...SSS...",
        ".SS...KS.",
        ".S.....S.",
        "M.......S",
        "S.......S",
        "S.......S",
        ".S.....S.",
        ".SK.L.SS.",
        "...SSS...",
      ],
      [ // Layer 8
        "...SSS...",
        ".SS...SS.",
        ".M.....S.",
        "S.......S",
        "S.......K",
        "S.......S",
        ".S.....S.",
        ".SS.L.SS.",
        "...SSS...",
      ],
      [ // Layer 9 — arrow slits again
        "...S.S...",
        ".SS...SS.",
        ".S.....S.",
        "S.......S",
        ".........",
        "S.......S",
        ".S.....S.",
        ".SS.L.SS.",
        "...S.S...",
      ],
      [ // Layer 10
        "...SSS...",
        ".SS...SS.",
        ".S.....M.",
        "S.......S",
        "S.......S",
        "K.......S",
        ".S.....S.",
        ".SS.L.SS.",
        "...SSS...",
      ],
      [ // Layer 11 — battlement deck (ladder hatch at the back)
        "...SSS...",
        ".SSSSSSS.",
        ".SPPPPPS.",
        "SPPPPPPPS",
        "SPPPPPPPS",
        "SPPPPPPPS",
        ".SPPPPPS.",
        ".SSSLSSS.",
        "...SSS...",
      ],
      [ // Layer 12 — crenellations
        "...S.S...",
        ".S.....S.",
        ".........",
        "S.......S",
        ".........",
        "S.......S",
        ".........",
        ".S.....S.",
        "...S.S...",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "wheat_farm",
    name: "Enclosed Wheat Farm",
    category: "Farm",
    difficulty: "Beginner",
    description:
      "An 11×11 fenced wheat farm. One central water block hydrates every farmland tile " +
      "(water reaches 4 blocks in every direction), and the slab-and-torch cap keeps you from falling in.",
    tips: [
      "Till the dirt with a hoe, then plant seeds — the single water source hydrates the whole 9×9 field.",
      "The center torch stops mobs spawning there and keeps nearby crops growing at night — add lanterns along the fence to light the whole field.",
      "Swap wheat for carrots or potatoes — the layout is identical.",
    ],
    legend: {
      L: "oak_log",
      F: "farmland",
      W: "water",
      w: "wheat_crop",
      f: "oak_fence",
      g: "oak_fence_gate",
      H: "oak_slab",
      t: "torch",
    },
    layers: [
      [ // Layer 1 — field
        "LLLLLLLLLLL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LFFFFWFFFFL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LFFFFFFFFFL",
        "LLLLLLLLLLL",
      ],
      [ // Layer 2 — fence, gate, crops
        "fffffgfffff",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fwwwwHwwwwf",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fwwwwwwwwwf",
        "fffffffffff",
      ],
      [ // Layer 3 — center torch
        "...........",
        "...........",
        "...........",
        "...........",
        "...........",
        ".....t.....",
        "...........",
        "...........",
        "...........",
        "...........",
        "...........",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "classic_fountain",
    name: "Classic Fountain",
    category: "Decoration",
    difficulty: "Beginner",
    description:
      "A 7×7 stone-brick plaza fountain. Water placed on the chiseled pillar cascades " +
      "down into the basin — the timeless village centerpiece.",
    tips: [
      "Place the pillar water LAST, from the top, and it will flow down evenly on all sides.",
      "Fill the basin corners first so the flowing water settles nicely.",
      "Ring it with a path and some lamp posts to anchor a village square.",
    ],
    legend: {
      S: "stone_bricks",
      C: "chiseled_stone_bricks",
      W: "water",
    },
    layers: [
      [ // Layer 1 — plaza pad
        "SSSSSSS",
        "SSSSSSS",
        "SSSSSSS",
        "SSSSSSS",
        "SSSSSSS",
        "SSSSSSS",
        "SSSSSSS",
      ],
      [ // Layer 2 — basin + pillar base
        "SSSSSSS",
        "SWWWWWS",
        "SWWWWWS",
        "SWWCWWS",
        "SWWWWWS",
        "SWWWWWS",
        "SSSSSSS",
      ],
      [ // Layer 3 — pillar
        ".......",
        ".......",
        ".......",
        "...C...",
        ".......",
        ".......",
        ".......",
      ],
      [ // Layer 4 — spout water
        ".......",
        ".......",
        ".......",
        "...W...",
        ".......",
        ".......",
        ".......",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "lighthouse",
    name: "Striped Lighthouse",
    category: "Landmark",
    difficulty: "Intermediate",
    description:
      "A 16-block red-and-white concrete lighthouse with a stone-brick base, iron-bar " +
      "gallery railing, glass lamp room and a sea lantern beacon you can spot from far out at sea.",
    tips: [
      "Count your bands before you start: 2 white, 2 red, repeating — mis-counting one band is very visible.",
      "Sea lanterns don't flicker like torches; use one (or a beacon!) for the lamp.",
      "Build it on a cliff or breakwater — lighthouses look wrong on flat inland ground.",
    ],
    legend: {
      B: "stone_bricks",
      W: "white_concrete",
      R: "red_concrete",
      G: "glass",
      S: "sea_lantern",
      i: "iron_bars",
      H: "stone_brick_slab",
      D: "spruce_door",
      E: "end_rod",
    },
    layers: [
      [ // Layer 1 — stone base
        "..BBB..",
        ".BBBBB.",
        "BBBBBBB",
        "BBBBBBB",
        "BBBBBBB",
        ".BBBBB.",
        "..BBB..",
      ],
      [ // Layer 2 — white + door
        "..WDW..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 3 — white (above door open)
        "..W.W..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 4 — red band
        "..RRR..",
        ".R...R.",
        "R.....R",
        "R.....R",
        "R.....R",
        ".R...R.",
        "..RRR..",
      ],
      [ // Layer 5 — red band
        "..RRR..",
        ".R...R.",
        "R.....R",
        "R.....R",
        "R.....R",
        ".R...R.",
        "..RRR..",
      ],
      [ // Layer 6 — white band
        "..WWW..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 7 — white band
        "..WWW..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 8 — red band
        "..RRR..",
        ".R...R.",
        "R.....R",
        "R.....R",
        "R.....R",
        ".R...R.",
        "..RRR..",
      ],
      [ // Layer 9 — red band
        "..RRR..",
        ".R...R.",
        "R.....R",
        "R.....R",
        "R.....R",
        ".R...R.",
        "..RRR..",
      ],
      [ // Layer 10 — white band
        "..WWW..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 11 — white band
        "..WWW..",
        ".W...W.",
        "W.....W",
        "W.....W",
        "W.....W",
        ".W...W.",
        "..WWW..",
      ],
      [ // Layer 12 — gallery deck
        "..WWW..",
        ".WWWWW.",
        "WWWWWWW",
        "WWWWWWW",
        "WWWWWWW",
        ".WWWWW.",
        "..WWW..",
      ],
      [ // Layer 13 — railing + lamp room + beacon
        "..iii..",
        ".i...i.",
        "i.GGG.i",
        "i.GSG.i",
        "i.GGG.i",
        ".i...i.",
        "..iii..",
      ],
      [ // Layer 14 — lamp room glass
        ".......",
        ".......",
        "..GGG..",
        "..G.G..",
        "..GGG..",
        ".......",
        ".......",
      ],
      [ // Layer 15 — lamp roof
        ".......",
        ".......",
        "..HHH..",
        "..HHH..",
        "..HHH..",
        ".......",
        ".......",
      ],
      [ // Layer 16 — finial
        ".......",
        ".......",
        ".......",
        "...E...",
        ".......",
        ".......",
        ".......",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "stone_bridge",
    name: "Stone Bridge",
    category: "Infrastructure",
    difficulty: "Beginner",
    description:
      "A 15-block stone-brick bridge with three support piers, walled railings, lantern " +
      "posts and stair approaches at both ends. Stretch or shrink it to fit your river.",
    tips: [
      "The three piers land on the riverbed — extend them down as far as your river is deep.",
      "To lengthen the bridge, repeat the middle deck section; keep a lantern every 4 blocks.",
      "Mossy stone bricks near the waterline sell the 'old bridge' look.",
    ],
    legend: {
      S: "stone_bricks",
      M: "mossy_stone_bricks",
      A: "stone_brick_stairs",
      W: "stone_brick_wall",
      n: "lantern",
    },
    layers: [
      [ // Layer 1 — piers
        "..S....S....S..",
        "..S....S....S..",
        "..S....S....S..",
        "..S....S....S..",
        "..S....S....S..",
      ],
      [ // Layer 2 — deck with stair approaches
        "ASSSMSSSSSSSSSA",
        "ASSSSSSSSMSSSSA",
        "ASSSSSSSSSSSSSA",
        "ASMSSSSSSSSSSSA",
        "ASSSSSSSSSMSSSA",
      ],
      [ // Layer 3 — railings
        ".WWWWWWWWWWWWW.",
        "...............",
        "...............",
        "...............",
        ".WWWWWWWWWWWWW.",
      ],
      [ // Layer 4 — lanterns
        "...n...n...n...",
        "...............",
        "...............",
        "...............",
        "...n...n...n...",
      ],
    ],
  },

  /* ---------------------------------------------------------- */
  {
    id: "nether_portal",
    name: "Nether Portal Gate",
    category: "Utility",
    difficulty: "Beginner",
    description:
      "A standard 4×5 obsidian portal frame on a cobbled deepslate pad, with crying-obsidian " +
      "corners (corners are decorative — the game only needs the 10 edge blocks) and soul lanterns.",
    tips: [
      "Light the inside of the frame with flint and steel to activate the portal.",
      "The 4 corners can be ANY block — crying obsidian just looks the part and you save 4 obsidian if you skip them.",
      "Soul lanterns match the portal's glow and keep the pad mob-free.",
    ],
    legend: {
      C: "cobbled_deepslate",
      O: "obsidian",
      c: "crying_obsidian",
      s: "soul_lantern",
    },
    layers: [
      [ // Layer 1 — pad
        "CCCCCC",
        "CCCCCC",
        "CCCCCC",
      ],
      [ // Layer 2 — frame bottom + lanterns
        "s....s",
        ".cOOc.",
        "......",
      ],
      [ // Layer 3 — frame sides
        "......",
        ".O..O.",
        "......",
      ],
      [ // Layer 4 — frame sides
        "......",
        ".O..O.",
        "......",
      ],
      [ // Layer 5 — frame sides
        "......",
        ".O..O.",
        "......",
      ],
      [ // Layer 6 — frame top
        "......",
        ".cOOc.",
        "......",
      ],
    ],
  },
];

/* Derived size info (validated on load in app.js). */
TEMPLATES.forEach((t) => {
  t.height = t.layers.length;
  t.depth = t.layers[0].length;
  t.width = t.layers[0][0].length;
  t.size = `${t.width}×${t.depth}×${t.height}`;
});
